power: supply: add some missing fix compiler errors
../sound/soc/msm/qdsp6v2/msm-pcm-routing-v2.c:16932:2: error: unterminated conditional directive

../drivers/power/supply/qcom/qpnp-smb2.c:2553:2: error: unterminated conditional directive

../drivers/power/supply/qcom/qpnp-fg-gen3.c:663:11: error: use of undeclared identifier 'buf'
        temp = ((buf[1] & BATT_TEMP_MSB_MASK) << 8) |
                 ^
../drivers/power/supply/qcom/qpnp-fg-gen3.c:664:4: error: use of undeclared identifier 'buf'
                (buf[0] & BATT_TEMP_LSB_MASK)

                ../drivers/power/supply/qcom/smb-lib.c:3664:3: error: use of undeclared identifier 'usb_alert_usb_otg_disable'
                usb_alert_usb_otg_disable=true;
                ^
../drivers/power/supply/qcom/smb-lib.c:3665:3: error: use of undeclared identifier 'need_replugin_usb'
                need_replugin_usb=false;
                ^
  CC      drivers/platform/msm/ipa/ipa_v2/teth_bridge.o
../drivers/power/supply/qcom/smb-lib.c:3676:25: error: use of undeclared identifier 'CHG_ALERT_HOT_NTC_VOLTAFE'
        }else if((phy_volta >= CHG_ALERT_HOT_NTC_VOLTAFE) && (phy_volta <= CHG_ALERT_WARM_NTC_VOLTAGE)){
                               ^
../drivers/power/supply/qcom/smb-lib.c:3676:69: error: use of undeclared identifier 'CHG_ALERT_WARM_NTC_VOLTAGE'
        }else if((phy_volta >= CHG_ALERT_HOT_NTC_VOLTAFE) && (phy_volta <= CHG_ALERT_WARM_NTC_VOLTAGE)){
                                                                           ^
../drivers/power/supply/qcom/smb-lib.c:3677:6: error: use of undeclared identifier 'usb_alert_usb_otg_disable'
                if(usb_alert_usb_otg_disable == true){
                   ^
../drivers/power/supply/qcom/smb-lib.c:3682:24: error: use of undeclared identifier 'CHG_ALERT_WARM_NTC_VOLTAGE'
        }else if((phy_volta > CHG_ALERT_WARM_NTC_VOLTAGE) && need_replugin_usb){
                              ^
../drivers/power/supply/qcom/smb-lib.c:3682:55: error: use of undeclared identifier 'need_replugin_usb'
        }else if((phy_volta > CHG_ALERT_WARM_NTC_VOLTAGE) && need_replugin_usb){
                                                             ^
../drivers/power/supply/qcom/smb-lib.c:3683:3: error: implicit declaration of function 'switch_set_state' [-Werror,-Wimplicit-function-declaration]
                switch_set_state(&usb_alert_dev, THM_ALERT_NONE);
                ^
../drivers/power/supply/qcom/smb-lib.c:3683:21: error: use of undeclared identifier 'usb_alert_dev'
                switch_set_state(&usb_alert_dev, THM_ALERT_NONE);
                                  ^
../drivers/power/supply/qcom/smb-lib.c:3683:36: error: use of undeclared identifier 'THM_ALERT_NONE'
                switch_set_state(&usb_alert_dev, THM_ALERT_NONE);
                                                 ^
../drivers/power/supply/qcom/smb-lib.c:3684:3: error: use of undeclared identifier 'usb_alert_usb_otg_disable'
                usb_alert_usb_otg_disable=false;
                ^
../drivers/power/supply/qcom/smb-lib.c:3685:3: error: use of undeclared identifier 'need_replugin_usb'
                need_replugin_usb=false;
                ^
../drivers/power/supply/qcom/smb-lib.c:3839:5: error: use of undeclared identifier 'usb_otg_present'
        if(usb_otg_present){
           ^
../drivers/power/supply/qcom/smb-lib.c:3858:4: error: implicit declaration of function 'CHG_DBG' [-Werror,-Wimplicit-function-declaration]
                        CHG_DBG("%s: charger limit is enable & over, stop charging\n", __func__);
                        ^
../drivers/power/supply/qcom/smb-lib.c:3947:4: error: implicit declaration of function 'CHG_DBG_E' [-Werror,-Wimplicit-function-declaration]
                        CHG_DBG_E("%s: Failed to set USBIN_CURRENT_LIMIT\n", __func__);
                        ^
../drivers/power/supply/qcom/smb-lib.c:4074:3: error: implicit declaration of function 'CHG_DBG_E' [-Werror,-Wimplicit-function-declaration]
                CHG_DBG_E("%s: Failed to set USBIN_OPTIONS_1_CFG_REG\n", __func__);
                ^
../drivers/power/supply/qcom/smb-lib.c:4227:4: error: implicit declaration of function 'CHG_DBG_E' [-Werror,-Wimplicit-function-declaration]
                        CHG_DBG_E("%s: Failed to set USBIN_CURRENT_LIMIT\n", __func__);

Signed-off-by: wimbiyoas <wyoashizkia@gmail.com>